object AndroidModuleDependencies {

    val ANDROID_APP_COMPAT = Dependencies.ANDROID_APP_COMPAT
    val ANDROID_CONSTRAINT_LAYOUT = Dependencies.ANDROID_CONSTRAINT_LAYOUT
    val ANDROID_RECYCLER_VIEW = Dependencies.ANDROID_RECYCLER_VIEW
    val ANDROID_MATERIAL_DESIGN = Dependencies.ANDROID_MATERIAL_DESIGN
    val ANDROID_CARD_VIEW = Dependencies.ANDROID_CARD_VIEW
    val ANDROID_COORDINATOR_LAYOUT = Dependencies.ANDROID_COORDINATOR_LAYOUT
    val ANDROID_CIRCLE_VIEW = Dependencies.ANDROID_CIRCLE_VIEW
    val ANDROID_ARCH_COMMON = Dependencies.ANDROID_ARCH_COMMON
    val ANDROID_ARCH_RUNTIME = Dependencies.ANDROID_ARCH_RUNTIME
    val ANDROID_ARCH_LIFECYCLE = Dependencies.ANDROID_ARCH_LIFECYCLE
    val ANDROID_ARCH_LIFECYCLE_EXT = Dependencies.ANDROID_ARCH_LIFECYCLE_EXT
    val ANDROID_ARCH_LIFECYCLE_VIEWMODEL = Dependencies.ANDROID_ARCH_LIFECYCLE_VIEWMODEL
    val ANDROID_ARCH_LIFECYCLE_RUNTIME = Dependencies.ANDROID_ARCH_LIFECYCLE_RUNTIME
    val ANDROID_COIL = Dependencies.ANDROID_COIL
    val ANDROID_EXO_PLAYER = Dependencies.ANDROID_EXO_PLAYER
    val AAAAH_CORE = Dependencies.AAAAH_CORE
    val AAAAH_LIBRARY = Dependencies.AAAAH_LIBRARY
    val AAAAH_ANNOTATION = Dependencies.AAAAH_ANNOTATION
    val AAAAH_COMPILER = Dependencies.AAAAH_COMPILER
    val DAGGER_COMPILER = Dependencies.DAGGER_COMPILER
    val DAGGER_ANDROID_PROCESSOR = Dependencies.DAGGER_ANDROID_PROCESSOR
    val DAGGER_CORE = Dependencies.DAGGER_CORE
    val DAGGER_ANDROID_SUPPORT = Dependencies.DAGGER_ANDROID_SUPPORT
    val KLAXON = Dependencies.KLAXON
    val KOTLIN_COROUTINES_JVM = Dependencies.KOTLIN_COROUTINES_JVM
    val KOTLIN_COROUTINES_ANDORID = Dependencies.KOTLIN_COROUTINES_ANDROID
    val LOGGER_ANDROID = Dependencies.LOGGER_ANDROID
    val LOGGER_ANDROID_TIMBER = Dependencies.LOGGER_ANDROID_TIMBER
    val PHOTO_VIEW = Dependencies.PHOTO_VIEW
}