enum class Dependencies(
    override val library: String,
    override val version: String
) : Dependency {

    KOTLIN_COMMON(library = "org.jetbrains.kotlin:kotlin-stdlib-common", version = "1.3.61"),
    KOTLIN_COROUTINES_COMMON(library = "org.jetbrains.kotlinx:kotlinx-coroutines-core-common", version = "1.3.3"),
    KOTLIN_COROUTINES_JVM(library = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.3.3"),
    KOTLIN_COROUTINES_ANDROID(library = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.3.3"),
    KOTLIN_JVM(library = "org.jetbrains.kotlin:kotlin-stdlib", version = "1.3.61"),
    JAVA_INJECT(library = "javax.inject:javax.inject", version = "1"),
    ANDROID_APP_COMPAT(library = "androidx.appcompat:appcompat", version = "1.1.0"),
    ANDROID_CONSTRAINT_LAYOUT(library = "androidx.constraintlayout:constraintlayout", version = "1.1.3"),
    ANDROID_RECYCLER_VIEW(library = "androidx.recyclerview:recyclerview", version = "1.2.0-alpha01"),
    ANDROID_MATERIAL_DESIGN(library = "com.google.android.material:material", version = "1.0.0"),
    ANDROID_CARD_VIEW(library = "androidx.cardview:cardview", version = "1.0.0"),
    ANDROID_COORDINATOR_LAYOUT(library = "androidx.coordinatorlayout:coordinatorlayout", version = "1.1.0"),
    ANDROID_CIRCLE_VIEW(library = "de.hdodenhof:circleimageview", version = "3.0.1"),
    ANDROID_ARCH_COMMON(library = "androidx.arch.core:core-common", version = "2.1.0"),
    ANDROID_ARCH_RUNTIME(library = "androidx.arch.core:core-runtime", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE(library = "androidx.lifecycle:lifecycle-common", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_EXT(library = "androidx.lifecycle:lifecycle-extensions", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_VIEWMODEL(library = "androidx.lifecycle:lifecycle-viewmodel", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_RUNTIME(library = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.2.0-rc03"),
    ANDROID_COIL(library = "io.coil-kt:coil", version = "0.8.0"),
    ANDROID_EXO_PLAYER(library = "com.google.android.exoplayer:exoplayer", version = "2.11.1"),
    AAAAH_CORE(library = "com.chrynan:aaaah-core", version = "0.3.3"),
    AAAAH_LIBRARY(library = "com.chrynan:aaaah-libraryx", version = "0.3.3"),
    AAAAH_ANNOTATION(library = "com.chrynan:aaaah-annotation", version = "0.3.3"),
    AAAAH_COMPILER(library = "com.chrynan:aaaah-compiler", version = "0.3.3"),
    DAGGER_COMPILER(library = "com.google.dagger:dagger-compiler", version = "2.19"),
    DAGGER_ANDROID_PROCESSOR(library = "com.google.dagger:dagger-android-processor", version = "2.19"),
    DAGGER_CORE(library = "com.google.dagger:dagger", version = "2.19"),
    DAGGER_ANDROID_SUPPORT(library = "com.google.dagger:dagger-android-support", version = "2.19"),
    KLAXON(library = "com.beust:klaxon", version = "5.0.1")
}