enum class Dependencies(
    override val path: String,
    override val version: String
) : Dependency {

    KOTLIN_COMMON(path = "org.jetbrains.kotlin:kotlin-stdlib-common", version = "1.3.61"),
    KOTLIN_COROUTINES_COMMON(path = "org.jetbrains.kotlinx:kotlinx-coroutines-core-common", version = "1.3.3"),
    KOTLIN_COROUTINES_JVM(path = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.3.3"),
    KOTLIN_COROUTINES_ANDROID(path = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.3.3"),
    KOTLIN_JVM(path = "org.jetbrains.kotlin:kotlin-stdlib", version = "1.3.61"),
    JAVA_INJECT(path = "javax.inject:javax.inject", version = "1"),
    ANDROID_APP_COMPAT(path = "androidx.appcompat:appcompat", version = "1.1.0"),
    ANDROID_CONSTRAINT_LAYOUT(path = "androidx.constraintlayout:constraintlayout", version = "1.1.3"),
    ANDROID_RECYCLER_VIEW(path = "androidx.recyclerview:recyclerview", version = "1.2.0-alpha01"),
    ANDROID_MATERIAL_DESIGN(path = "com.google.android.material:material", version = "1.0.0"),
    ANDROID_CARD_VIEW(path = "androidx.cardview:cardview", version = "1.0.0"),
    ANDROID_COORDINATOR_LAYOUT(path = "androidx.coordinatorlayout:coordinatorlayout", version = "1.1.0"),
    ANDROID_CIRCLE_VIEW(path = "de.hdodenhof:circleimageview", version = "3.0.1"),
    ANDROID_ARCH_COMMON(path = "androidx.arch.core:core-common", version = "2.1.0"),
    ANDROID_ARCH_RUNTIME(path = "androidx.arch.core:core-runtime", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE(path = "androidx.lifecycle:lifecycle-common", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_EXT(path = "androidx.lifecycle:lifecycle-extensions", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_VIEWMODEL(path = "androidx.lifecycle:lifecycle-viewmodel", version = "2.1.0"),
    ANDROID_ARCH_LIFECYCLE_RUNTIME(path = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.2.0-rc03"),
    ANDROID_COIL(path = "io.coil-kt:coil", version = "0.8.0"),
    ANDROID_EXO_PLAYER(path = "com.google.android.exoplayer:exoplayer", version = "2.11.1"),
    AAAAH_CORE(path = "com.chrynan.aaaah:aaaah-core", version = "0.6.0"),
    AAAAH_CORE_JVM(path = "com.chrynan.aaaah:aaaah-core-jvm", version = "0.6.0"),
    AAAAH_LIBRARY(path = "com.chrynan.aaaah:aaaah-libraryx", version = "0.6.0"),
    AAAAH_ANNOTATION(path = "com.chrynan.aaaah:aaaah-annotation", version = "0.6.0"),
    AAAAH_COMPILER(path = "com.chrynan.aaaah:aaaah-compiler", version = "0.6.0"),
    DAGGER_COMPILER(path = "com.google.dagger:dagger-compiler", version = "2.19"),
    DAGGER_ANDROID_PROCESSOR(path = "com.google.dagger:dagger-android-processor", version = "2.19"),
    DAGGER_CORE(path = "com.google.dagger:dagger", version = "2.19"),
    DAGGER_ANDROID_SUPPORT(path = "com.google.dagger:dagger-android-support", version = "2.19"),
    KLAXON(path = "com.beust:klaxon", version = "5.0.1"),
    LOGGER(path = "com.chrynan.logger:logger-core", version = "1.2.1"),
    LOGGER_ANDROID(path = "com.chrynan.logger:logger-android", version = "1.2.1"),
    LOGGER_ANDROID_TIMBER(path = "com.chrynan.logger:logger-android-timber", version = "1.2.1")
}